"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var insertMiddle_1 = require("./insertMiddle");
var arr = [''];
insertMiddle_1.insertMiddle([1], arr);
console.log(arr);
insertMiddle_1.insertMiddle([2], arr);
console.log(arr);
insertMiddle_1.insertMiddle([3], arr);
console.log(arr);
insertMiddle_1.insertMiddle([4], arr);
console.log(arr);
insertMiddle_1.insertMiddle([5], arr);
console.log(arr);
insertMiddle_1.insertMiddle([6], arr);
console.log(arr);
insertMiddle_1.insertMiddle([7], arr);
console.log(arr);
insertMiddle_1.insertMiddle([8], arr);
console.log(arr);
insertMiddle_1.insertMiddle([9], arr);
console.log(arr);
insertMiddle_1.insertMiddle([10], arr);
console.log(arr);
insertMiddle_1.insertMiddle([11, 12], arr);
console.log(arr);
insertMiddle_1.insertMiddle([], arr);
console.log(arr);
insertMiddle_1.insertMiddle(['aaa'], arr);
console.log(arr);
insertMiddle_1.insertMiddle(['bbb'], arr);
console.log(arr);
